name = "dev-leolem-alert"
main = "tool/alert.ts"
compatibility_date = "2026-02-15"

routes = [{ pattern = "alert.leolem.dev/*", zone_name = "leolem.dev" }]

[vars]
ALLOWED_ORIGINS = "https://leolem.dev,http://localhost:4321"